# Generated by Django 4.1.5 on 2023-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveSmallIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('firstlogin', models.BooleanField(default=False)),
                ('usertype', models.CharField(default='buyer', max_length=100)),
            ],
        ),
    ]
